# build
FROM golang:1.17.1-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o auth .

# run
FROM scratch
WORKDIR /build
COPY --from=builder /src/auth .
ENTRYPOINT [ "/build/auth" ]
