apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: flurach/auth
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: ENV
          value: qa
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: NodePort
  selector:
    app: auth
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
